name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: backend

    steps:
    - uses: actions/checkout@v4
    - name: List files in directory
      run: ls -l

    - name: Build the Docker image
      run: |
        echo "Building Docker image..."
        docker build . --tag pixel-app:$(date +%s)