name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set working directory
      run: cd backend

    - name: Build the Docker image
      run: docker build . --tag pixel-app:$(date +%s)