name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set working directory
      run: |
        echo "Current directory before changing: $(pwd)"
        cd backend
        echo "Current directory after changing: $(pwd)"

    - name: List files in directory
      run: ls -l

    - name: Build the Docker image
      run: |
        echo "Building Docker image..."
        docker build . --tag pixel-app:$(date +%s)