name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        working-directory: backend
        run: |
          docker build . --file Dockerfile --tag pixel-app:$(date +%s)

      - name: Run tests
        working-directory: backend
        run: |
          docker run --rm pixel-app:$(date +%s)