name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        working-directory: backend
        run: |
          IMAGE_TAG=$(date +%s)
          docker build . --file Dockerfile --tag pixel-app-production:$IMAGE_TAG

      - name: Run tests (volume mount)
        working-directory: backend
        run: |
          docker run --rm pixel-app-production:$IMAGE_TAG pytest --verbose -v=::host 
          # -v=::host maps the host's working directory to /app within the container